### PR TITLE
Use Stable Crontab Library Version

### PR DESCRIPTION
**Pull request by maennchen**

### CODE REVIEW

**Comment by maennchen** [comment]
@c-rack Do we need additional changes to make a new stable release?

Since all of the Parser Module were `@moduledoc false`, do we need to make a new major release or is a minor one enough?

**Comment by c-rack** [comment]
@maennchen sorry for late reply and merge. a minor version bump should be ok, as there are no changes (only extensions) to the API itself, right?

**Comment by maennchen** [comment]
@c-rack I think so. I'm going to add the umbrella support too for the next release.

**Comment by c-rack** [comment]
OK, let me know when you are ready for the next release.

**Pull request merged**
