### PR TITLE
Solution: Fix Dialyzer Warnings

### PR DESCRIPTION
**Pull request by maennchen**
Partial Fix for #246

### CODE REVIEW

**Comment by maennchen** [comment]
It'd be nice if anyone had an idea on how to solve those two issues.

I posted into Elixirforum for help. https://elixirforum.com/t/dialyzer-the-created-fun-has-no-local-return/8247

**Comment by maennchen** [comment]
@c-rack Can we merge this one even though it only solves 1/2 of the issue?

I have no idea why the rest is failing and need someone else to help me / fix it.

**Comment by c-rack** [comment]
@maennchen Sure, even a partial fix is worth a PR and a merge. The remaining warings can be addressed by another one if someone has an idea how to fix them.

**Comment by maennchen** [comment]
Should we wait with the release until those warnings are fixed or should I create a release for `v2.1.0`?

**Pull request merged**
