### PR TITLE
Readme updates for version 2.0

### PR DESCRIPTION
**Pull request by matthewlehner**
This includes a couple documentation updates for setting up Quantum with the changes from 2.0

Once a 2.0 beta version is released on hex the version listed in `deps` should be updated, but that is waiting on #184

### CODE REVIEW

**Comment by c-rack** [comment]
Thanks!

**Comment by maennchen** [comment]
Why was timex removed from the applications? The list entry is needed for the default configuration.

**Comment by c-rack** [comment]
Sorry, I missed that. I'll send a PR to fix that.

**Comment by matthewlehner** [comment]
Ah, sorry about that – was travelling until today so didn't have a chance to respond.

I'd wrongly assumed that Timex was only necessary for timezone support beyond UTC.

**Pull request merged**
