### PR TITLE
Problem: Named jobs #16

### PR DESCRIPTION
**Pull request by alPacino**

### CODE REVIEW

**Comment by c-rack** [comment]
Thanks, could you please rebase your changes against current master to make it mergeable?

**Comment by alPacino** [comment]
Doing this right now :)

**Comment by c-rack** [comment]
Thanks. Please note that according to [the C4.1 process](http://rfc.zeromq.org/spec:22):
> Maintainers SHOULD NOT merge their own patches except in exceptional cases, such as non-responsiveness from other Maintainers for an extended period (more than 1-2 days).

Just a hint for future pull requests :)

**Comment by alPacino** [comment]
Ok, thanks, will read this :)

**Pull request merged**
