### PR TITLE
#104 Umbrella Configuration

### PR DESCRIPTION
**Pull request by maennchen**
Implementation of #104

### CODE REVIEW

**Comment by andrejsm** [comment]
Wouldn't this make confusion to have at least 2 places where to configure `:quantum`?
```elixir
config :quantum, global?: true

config :quantum, :my_app, cron: [ ... ]
```

My first impression was that I could also make specific app jobs to be global:
```elixir
config :quantum, :my_app,
  global?: true,
  cron: [ ... ]
```
but this is not true.

Probably all config should be name-spaced. In which case apps not being under umbrella should be name-spaced as well.

**Comment by maennchen** [comment]
If all configurations are namespaced, we'd have to introduce one executor per app instead of a central one. This would be something for `v2` and a major refactoring.

**Comment by c-rack** [comment]
Only one wish for upcoming commit messages: it would be great if you could follow our Problem/Solution style :-)

**Comment by andrejsm** [comment]
Fair enough. Thanks!

**Pull request merged**
