### PR TITLE
Problem: calendar dependency is outdated

### PR DESCRIPTION
**Pull request by c-rack**
Solution: update to latest 0.17.*

### CODE REVIEW

**Comment by maennchen** [comment]
Do we have any requirements that need the newer version? The old version requirement includes the 0.17 version. As long as the dependency is >= 1.0.0 this version requirement works.

**Comment by c-rack** [comment]
You are right, `~> 0.16` also covers `0.17.x`. In this project, I just try to keep the dependencies as up-to-date as possible (see commit history), that's the only reason for this update. Also, I prefer to refer only to major and minor version of the dependencies, so I made the `crontab` dep consistent with that.

**Comment by maennchen** [comment]
@c-rack I'm not sure this is something useful to do. When we put `~> 0.17`, someone with a dependency to specifically `calendar` `0.16` is not able to use the quantum library.

I'm totally in to keep the major versions up to date. So if `calendar` releases `1.0` including BC breaks, we totally should update.

How do you see that?

**Comment by c-rack** [comment]
@maennchen My point of view is a little bit different: current 1.9.1 is published so if someone relies on 0.16 of calendar, one can still use quantum 1.9.1 without problems. I just want to have current HEAD always using the latest version its ecosystem, especially for testing purposes. Yes, 0.17 is included in `~> 0.16`, but always using latest dependency versions is also not a bad thing. This is how we have handled it in the past and we had no complaints about this practice:
https://github.com/c-rack/quantum-elixir/search?utf8=%E2%9C%93&q=outdated&type=Commits

Just as a side note, our C4 process is kind of "merge contributions fast, discuss or revert them later if neccessary". I learned this from @hintjens, who explained that in his EuroSciPy 2015 keynote: https://www.youtube.com/watch?v=O8CbzKREAj4 (start at 17:00, even if the whole keynote is worth watching)

**Comment by maennchen** [comment]
@c-rack Side-Note to you Side-Note:

> merge contributions fast, discuss or revert them later if neccessary

Won't we introduce BC breaks if we do that? If we merge a new feature and later revert it, users are going to complain...

**Comment by c-rack** [comment]
Did you watch the video? In most cases, contributions are useful and should, according to C4, solve a well-specified problem, so fast merges (without much discussion) are generally a good approach to give contributors (who have spent their valuable spare time to make the project better) an instant, positive feedback. Wrong, faulty, offending, etc. contributions are usually reverted very quickly and for sure before a new version is published, so it is unlikely that it would harm users. By the way that's why I don't like GitHub's new PR review feature in projects using C4, but that's another story :)

**Comment by maennchen** [comment]
@c-rack No, I haven't seen it by now, but I will do.

**Pull request merged**
