### PR TITLE
Problem: same task could be generated multiple times in a cluster

### PR DESCRIPTION
**Pull request by princemaple**
Solution: run quantum as a globally unique process in a cluster

Closes #102

### CODE REVIEW

**Comment by c-rack** [comment]
@princemaple looks good!

Would you mind to rewrite the commit message and the pull request title according to our "problem/solution" style? (see previous PRs and commits)

Also, it would help to include a `Fixes #101` in the pull request message, so the issue is automatically closed when the PR is merged.

**Comment by princemaple** [comment]
Yep, I'm looking at possible ways of testing right now. Will clean up the
PR when I finish it.

**Comment by princemaple** [comment]
Hi @c-rack , I can't seem to work out a way to test without interfering with other tests. Do you have any idea how it could be achieved?

**Comment by c-rack** [comment]
No, I don't. But it is ok as it is, coverage remained at 100% and your changes look good, so I'll merge it now. Thanks again for contributing!

**Pull request merged**
