### PR TITLE
Solution: Documentation not in ExDoc

### PR DESCRIPTION
**Pull request by maennchen**
Implementation of #162 

⚠️  As soon as this PR is merged, the documentation link in the README will point towards the hexdocs. A new version needs to be released immediately or people will not find the documentation.

I also commented out the documentation of the second granularity configuration, since it does not work because of #156.

### CODE REVIEW

**Comment by maennchen** [comment]
@c-rack What do you think ot the PR?

**Comment by c-rack** [comment]
I will merge and publish new version as soon as my time permits, was on business travel during the last days.

**Comment by princemaple** [comment]
Should we drop some links in readme to other pages other than configuration?

**Comment by maennchen** [comment]
@princemaple I found the confoguration page to be the most usefull entry point. Theres more links to continue from the configuration page.

What would be your suggestion?

**Comment by princemaple** [comment]
Was merely afraid that those pages could be hidden too deep.

**Comment by maennchen** [comment]
@princemaple The HexDoc page should be the "real" documentation. There is a clean navigation etc. for the documentation. I think it should be easy understandable.

**Comment by princemaple** [comment]
I agree re:real docs. :+1:
I sometimes get too obsessed with syncing github and hexdoc.

**Comment by maennchen** [comment]
@c-rack Ping (I don't want to annoy you if you're still busy, I'm just ensuring you didn't forget it. 😉 )

**Comment by c-rack** [comment]
@maennchen thanks for the friendly reminder, PR is merged and new version 1.9.1 is published

**Comment by maennchen** [comment]
@c-rack Thank you very much 🎉🎉

**Pull request merged**
