### PR TITLE
Add credo coder linter.

### PR DESCRIPTION
**Pull request by c-rack**
It could help us to improve and keep the code quality.

### CODE REVIEW

**Comment by c-rack** [comment]
@theoretick Feel free to merge this :-)

**Comment by c-rack** [comment]
also anyone of the other collaborators... :-)

**Comment by theoretick** [comment]
Nice! Been meaning to try this out :)

**Comment by c-rack** [comment]
Do you mean credo or merging the PR? :)

**Comment by theoretick** [comment]
Haha credo, but in retrospect why not both?

**Pull request merged**
