### PR TITLE
Solution: More Flexible Scheduler

### PR DESCRIPTION
**Pull request by maennchen**
Implementation of #207

### CODE REVIEW

**Comment by maennchen** [comment]
@princemaple What do you think about this?

How will this help to improve the tests?

**Comment by princemaple** [comment]
Good start, there are some other bits and pieces that are required before this part can really kick in. I'll try and work on quantum today.

**Comment by princemaple** [comment]
Please take a look at https://github.com/jshmrtn/quantum-elixir/pull/1
Also I sent https://github.com/c-rack/quantum-elixir/pull/216 to trigger the CI.

**Comment by maennchen** [comment]
@princemaple Thank you very much!

@c-rack Ready for review.

**Comment by c-rack** [comment]
@maennchen @princemaple thank you very much!

**Pull request merged**
