### PR TITLE
Solution: Support both Calendar, Timex & possibly other date libraries

### PR DESCRIPTION
**Pull request by maennchen**
Implementation of #176 

This PR has now Breaking Changes. It has to be released with the other `v2` PR's.

This PR depends on #181. Merge & Rebase first.

# Incomplete Tasks:

* [X] Implement Crontab Timex Behaviour
* [x] Implement Crontab Calendar Behaviour
* [ ] Modify crontab Version Number in `mix.exs`
* [X] Implement Quantum Timex Behaviour
* [x] Implement Quantum Calendar Behaviour

### CODE REVIEW

**Comment by c-rack** [comment]
@maennchen first of all, sorry for the late response, I have a really busy week and try to find the time to comment your contributions. Hope to catch up all issues and PRs this weekend.

We had merged #122 in the past, where @lau replaced timex with calendar for a specific reason. I would like to hear his feedback on switching back to timex before merging this. Maybe another option would be to use calendar instead of timex in the crontab project?

**Comment by lau** [comment]
How about having either be an optional dependency? They are only needed for doing timezone conversions in Elixir 1.3+. For cron-like tasks you would often want to use UTC. If you do need timezone support, quantum could have an adapter that depends on either Calendar or Timex. It could detect if one of them is present and use one if needed.

For Calendar and Timex some projects already have either of those as dependencies and some both. Some with specific versions. This can create conflicts if other libraries depend on specific versions of those.

A side not for the future: In Elixir 1.5 or 1.6 timezone/tzdata support will hopefully be in the standard library, so ideally either dependencies would not even be needed for timezone support.

**Comment by maennchen** [comment]
@lau Since the crontab library depends on timex, it will be pointless to make it optional.

**Comment by lau** [comment]
@maennchen My suggestion is to change quantum to no depend exclusively on it. Elixir has some built in functionality for date and time now. Maybe it is not necessary today as much as it was before, when Elixir didn't have date and time functionality in the standard library.

**Comment by maennchen** [comment]
@c-rack Crontab uses Timex on purpose. It needs to find the beginning an end of date ranges. (Months, Weeks, Days etc) this is very easy with timex, but I couldn't find those on calendar.

Have a look at those files:
https://github.com/jshmrtn/crontab/blob/master/lib/crontab/scheduler.ex
https://github.com/jshmrtn/crontab/blob/master/lib/crontab/date_checker.ex

**Comment by maennchen** [comment]
@lau What would it provide if timex is optional but it still relies on crontab where it is not optional?

The only good approach would be to make it optional in both places. I have used timex for a good reason in crontab though. There's many functions which I didn't find in calendar, but are present in timex.

**Comment by maennchen** [comment]
@lau 

Timex provides a much simpler interface for the following things:
* Mutating time in reasonable units. Like `Timex.shift(date, days: 1)`
* Getting the begin / end of a month `Timex.end_of_month(date)` and `Timex.beginning_of_month(date)`
* Getting the begin / end of a day `Timex.beginning_of_day(date)` and `Timex.end_of_day(date)`

If you provide me with a list of replacements, I will happily implement this via a behaviour => Date Lib independent.

**Comment by maennchen** [comment]
@lau 

Can you help me with the two TODO's?
https://github.com/jshmrtn/quantum-elixir/blob/feature/replace_calendar_with_timex/lib/quantum/date_library/calendar.ex

**Comment by maennchen** [comment]
I'd like to get this code merged.

Either I need support for the calendar implementation of both `quantum` and `crontab` ( @lau ?), or I propose we still provide the behaviour & `timex` adapter, but currently without `calendar` implementation.

**Comment by maennchen** [comment]
@c-rack ready

**Comment by maennchen** [comment]
Proposed: Merge now. `calendar` adapter can be added later when needed.

**Comment by maennchen** [comment]
General View on calendar libraries:

Support will (hopefully) be added in future elixir versions itself. The goal is to remove all calndar dependencies in the future.

**Pull request merged**
