### PR TITLE
No more warnings on gen_stage v0.13

### PR DESCRIPTION
**Pull request by ericentin**
This PR eliminates some warnings that are produced when you use the latest version of gen_stage with quantum, and relaxes the version requirement to include v0.13.1 (and any further versions prior to v1.0.0).

### CODE REVIEW

**Comment by c-rack** [comment]
@ericentin Thanks! 👍

**Comment by ericentin** [comment]
No rush, just curious: do you have an ETA on the next release? Thanks for quantum!

**Comment by c-rack** [comment]
There is no fixed ETA, we make a new release if there is demand from the community or if we have important changes that make a new release necessary. Maybe I'll release a new version with your changes this weekend.

**Comment by maennchen** [comment]
@ericentin My plan is to fix the PR #292 this week or weekend. After that I‘m going to make a release.

**Pull request merged**
