### PR TITLE
Some adaption for conform/exrm

### PR DESCRIPTION
**Pull request by alPacino**
@c-rack thanks for quantum first of all :)

I've got some troubles using quantum with exrm.
First I need to generate some configs like this:

```
$ mix conform.new
$ mix conform.configure
```

and after

```
$ mix conform.effective
```

it fails. Looks like it can't convert quantum's config into his own of release. I've tried many variants and decided to use simple form of configuration, just like in cron:

```
* * * * * MyApp.MyModule.my_method
```
Configuration looks like:
```
config :quantum, cron: [
    "* * * * * MyApp.MyModule.my_method"
]
```
Hope this will be useful for others.

### CODE REVIEW

**Comment by norbu09** [comment]
I think I ran into the same issue with `edeliver` which uses `exrm` under the hood.

**Comment by c-rack** [comment]
@alPacino Thanks! I will release a new version and publish to hex.pm shortly.

**Comment by c-rack** [comment]
So version 1.3.0 has been released to hex.pm.
However, the PR has [decreased the code coverage by 1.56%](https://coveralls.io/builds/3060649).
Fortunately, it is only one line not being covered.
Any volunteers to bring code coverage back to 100%? :smile:

**Comment by alPacino** [comment]
Sorry, it's my bad :) I'm on it. Will send another PR.
Also will add configuration example into README:
```
config :quantum, cron: [
    "* * * * *": {"MyApp.MyModule", :my_method}
]
```

**Pull request merged**
